name: austrian-flood-monitoring-db

services:
  db:
    container_name: flood-monitoring-db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  db-setup:
    container_name: flood-monitoring-db-setup
    image: oven/bun:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      ["sh", "-c", "bun install && bunx prisma migrate reset --force && bun run seed"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    container_name: flood-monitoring-backend
    image: oven/bun:latest
    volumes:
      - .:/app
    working_dir: /app
    command: ["bun", "serve"]
    ports:
      - 9512:9512
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
